apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nexabank
  namespace: nexabank
  labels:
    app.kubernetes.io/name: nexabank
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nexabank
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
