apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexabank

resources:
  - ../../base

labels:
  - includeSelectors: true
    pairs:
      environment: dev

patches:
  - target:
      kind: Deployment
      name: nexabank
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
      name: nexabank
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2

images:
  - name: ghcr.io/example/nexabank
    newTag: dev
